###
GRAPHQL http://localhost:8080/query

mutation createUser{
    createUser(username:"nikitaA", email: "nikitaki.@gmail.com"){
        id
        email
        username
    }
}
mutation createPost{
    createPost(userId: "", title: "",
        text: "", allowComments: true){
        id
        userId
        title
        text
        comments
        allowComments
    }
}
mutation createComment{
    createComment(userId: "", postId: "",
        parentId: "", text: "", ){
        id
        userId
        postId
        parentId
        text
        createdAt
        children
    }
}
